// Single source of truth for icon choices used across the app.
// Import icons from here (not directly from 'lucide-react') so every
// component agrees on which icon represents which concept.
export {
  MapPin as LocationIcon,
  Calendar as DateIcon,
  CircleCheck as CompletedIcon,
  Clock as TimeIcon,
  User as SpotsIcon,
  Bell as NotificationsIcon,
  Check as ChecklistIcon,
  Heart as SaveIcon,
  Building2 as OrganizationIcon,
  Pencil as EditIcon,
  Camera as UploadPhotoIcon,
  ChevronDown as DropdownIcon,
  LayoutDashboard as DashboardIcon,
  Search as BrowseOpportunitiesIcon,
  ClipboardList as RegistrationsIcon,
  User as ProfileIcon,
  Heart as FavoritesIcon,
  Mail as MessagesIcon,
  Settings as SettingsIcon,
  LogOut as LogOutIcon,
  Calendar as OpportunitiesIcon,
  Users as VolunteersIcon,
  Menu as MenuIcon,
  Lock as TeamAccessIcon,
  Shield as PermissionsIcon,
  Calendar as GoogleCalendarIcon,
  MessageSquare as SlackIntegrationIcon,
  FileSpreadsheet as CsvExportIcon,
  Download as DownloadIcon,
  KeyRound as PasswordIcon,
  ShieldCheck as TwoFactorIcon,
  Monitor as SessionManagementIcon,
  Trash2 as DeleteAccountIcon,
} from 'lucide-react'